-- Migration for the 0.2.0 application schema.
--
-- This file is intentionally destructive.  The application schema is still
-- under development and the old tables contain the pre-Keycloak user model.
-- Reviews are dropped first because older installations may have foreign keys
-- from reviews to that model.  Run it against minha_app_db (see README.md).
BEGIN;

DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Identity is provided by PostgreSQL; no application-managed sequence or
-- local user table is needed.  BY DEFAULT keeps the schema useful for data
-- imports while still making normal inserts auto-incrementing.
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    sku VARCHAR(100) NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT ck_products_price_nonnegative CHECK (price >= 0)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    -- The value is the Keycloak JWT `sub` claim.  It is deliberately not a
    -- foreign key: identity data belongs to Keycloak, not this database.
    user_keycloak_id VARCHAR(255) NOT NULL,
    comment TEXT NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (id),
    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT ck_reviews_comment_nonblank CHECK (length(btrim(comment)) > 0)
);

-- The FK is useful for joins, but explicit indexes also keep the two main
-- access paths (product page and user's own reviews) efficient.
CREATE INDEX ix_reviews_product_id ON reviews (product_id);
CREATE INDEX ix_reviews_user_keycloak_id ON reviews (user_keycloak_id);

COMMIT;
